import Head from 'next/head'
import NavBar from './components/navbar'
import styles from '../styles/Home.module.css'
import SideBar from './components/sidebar'
import Videos from './components/video'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>YouTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div class="flex">
        <SideBar/>
        <Videos/>
      </div>
    </div>
  )
}
